web/app1/urls.py
from django.conf.urls import url

from app1 import views

urlpatterns = [
    url(r'^helloworld/', views.helloworld, name='helloworld'),

    #url(r'^addarticle/', views.addarticle, name='addarticle'),

    url(r'^register/', views.register, name = 'register'),

    url(r'^get_verify_code/', views.get_verify_code, name = 'get_verify_code'),

    url(r'^checkusername/', views.check_username, name = 'check_username'),

    url(r'^login/', views.login, name = 'login'),

    url(r'^home/', views.home, name = 'home'),

    url(r'^logout/', views.logout, name = 'logout'),

    url(r'^addarticle/', views.add_article, name = 'add_article'),

    url(r'^article/(?P<article_id>\d+)', views.show_article, name = 'show_article'),

    url(r'^addlikerelationship/', views.add_like_relationship, name='add_like_relationship'),

    url(r'^recommendarticle/', views.recommend_article, name='recommend_article'),

    url(r'^markarticle/', views.mark_article, name='mark_article'),

    url(r'^addicon/', views.add_icon, name = 'add_icon'),

    url(r'^myblog/', views.my_blog, name = 'my_blog'),

    url(r'^changepassword/', views.change_password, name='change_password'),

    url(r'^changepasswordcheck/', views.change_password_check, name='change_password_check'),

    url(r'^deletearticle/(?P<article_id>\d+)/', views.delete_article, name = 'delete_article'),

    url(r'^personalinformation/', views.personal_information, name = 'personal_information'),

    url(r'^blogs/(?P<order_type>\d+)/', views.blogs, name = 'blogs'),

    url(r'^adddiscussion/', views.add_discussion, name = 'add_discussion'),

    url(r'^mydiscussion/', views.my_discussion, name='my_discussion'),

    url(r'^show_discussion/(?P<discussion_id>\d+)/(?P<order_type>\d+)/', views.show_discussion, name='show_discussion'),

    url(r'^discussions/', views.discussions, name = 'discussions'),

    url(r'^addarticlecomment/(?P<article_id>\d+)/', views.add_article_comment, name = 'add_article_comment'),

    url(r'^deletediscussion/(?P<discussion_id>\d+)/', views.delete_discussion, name = 'delete_discussion'),

    url(r'^recommenddiscussion/', views.recommend_discussion, name='recommend_discussion'),

    url(r'^markdiscussion/', views.mark_discussion, name='mark_discussion'),

    url(r'^adddiscussioncomment/(?P<discussion_id>\d+)/', views.add_discussion_comment, name = 'add_discussion_comment'),

    url(r'^recommenddiscussionresponse/(?P<comment_id>\d+)/(?P<fan_id>\d+)/', views.recommend_discussion_response, name = 'recommend_discussion_response'),

    url(r'^explore/', views.explore, name = 'explore'),

    url(r'^mycollectedarticles/', views.my_collected_articles, name = 'my_collected_articles'),

    url(r'^myfans/', views.my_fans, name = 'my_fans'),

    url(r'^myidols/', views.my_idols, name = 'my_idols'),
    #add functions
    url(r'^editblog/(?P<article_id>\d+)/', views.edit_blog, name='edit_blog'),

    url(r'^searchblog/', views.search_blog, name='search_blog'),

    url(r'^searchdiscussion/', views.search_discussion, name='search_discussion'),

    url(r'^searchuser/', views.search_user, name='search_user'),

    url(r'^hishome/(?P<person_id>\d+)/', views.his_home, name='his_home'),

    url(r'^hisblog/(?P<person_id>\d+)/', views.his_blog, name='his_blog'),

    url(r'^hisdiscussion/(?P<person_id>\d+)/', views.his_discussion, name='his_discussion'),

    url(r'^hisidols/(?P<person_id>\d+)/', views.his_idols, name='his_idols'),

    url(r'^hisfans/(?P<person_id>\d+)/', views.his_fans, name='his_fans'),

    url(r'^mycollecteddiscussions/', views.my_collected_discussions, name='my_collected_discussions'),

    url(r'^deletecomment/(?P<comment_id>\d+)/', views.delete_comment, name='delete_comment'),

    url(r'^deleteblogcomment/(?P<comment_id>\d+)/', views.delete_blog_comment, name='delete_blog_comment'),

    url(r'^unlikerelationship/', views.unlike_relationship, name='unlike_relationship'),

    url(r'^messagebox/', views.message_box, name='message_box'),

    url(r'^getlabel/(?P<label_type>\d+)/', views.get_label, name='get_label'),

    url(r'^getdlabel/(?P<label_type>\d+)/', views.get_d_label, name='get_d_label'),

    url(r'^addlabel/', views.add_label, name = 'add_label'),

    url(r'^randomdiscussion/', views.random_discussion, name='random_discussion'),

    url(r'^randomblog/', views.random_blog, name='random_blog'),

    url(r'^calculatehot/', views.calculate_hot, name='calculate_hot'),#刷新博客热度排名

    url(r'^chat/(?P<receiver_id>\d+)/(?P<sender_id>\d+)/', views.chat, name='chat'),

    url(r'^chatrooms/', views.chatrooms, name='chatrooms'),

    url(r'^deletechat/(?P<room_id>\d+)/', views.delete_chat, name='delete_chat'),

    url(r'^uncollectblog/(?P<article_id>\d+)/', views.uncollect_blog, name='uncollect_blog'),

    url(r'^uncollectdiscussion/(?P<discussion_id>\d+)/', views.uncollect_discussion, name='uncollect_discussion'),

    url(r'^resdisres/(?P<comment_id>\d+)/(?P<type>\d+)/(?P<discussion_id>\d+)/', views.res_dis_res, name='res_dis_res'),

    # url(r'^refreshlabel/', views.refresh_label, name = 'refresh_label'),

    url(r'^$', views.index, name='index'),

]

web/web1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('app1.urls', namespace='app1')),
]

web/templates/Discussion/add_comment.html
{% extends 'Discussion/base_discussion.html' %}

{% load static %}

{% block head %}
<script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        "mode": "textareas",
        "theme": "advanced",
        "width": 800,
        "height": 600,
    })
</script>
{% endblock %}

{% block content %}
    <form action="{% url 'app1:add_discussion_comment' discussion_id=discussion_id %}" method="post">
        {% csrf_token %}
        <span>内容：</span> <textarea name="content"></textarea>
        <button>保存</button>
    </form>
{% endblock %}

web/templates/Discussion/add_comment_response.html
{% extends 'Discussion/base_discussion.html' %}

{% load static %}

{% block head %}
<script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        "mode": "textareas",
        "theme": "advanced",
        "width": 800,
        "height": 600,
    })
</script>
{% endblock %}

{% block content %}
    <form action="{% url 'app1:res_dis_res' comment_id type discussion_id%}" method="post">
        {% csrf_token %}
        <span>内容：</span> <textarea name="content"></textarea>
        <button>保存</button>
    </form>
{% endblock %}

web/templates/Discussion/add_discussion.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'app1:add_discussion' %}" method="post">
        {% csrf_token %}
        <span>标题：</span> <input type="text" name="title" value="标题.."> <br>
        <div id="div1" class="toolbar">
        </div>
        <div style="padding: 5px 0; color: #ccc"> </div>
        <div id="div2" class="text">
            <p>请输入内容..</p>
        </div>
        <textarea name="content" id="text1" style="display:none"></textarea>
        <span>添加标签,让你的问题被更多人看到!</span><br>
        <span>学习区</span>
        <input type="checkbox" value="1" name="item" onClick="onCheckBox(this)">高等数学
        <input type="checkbox" value="2" name="item" onClick="onCheckBox(this)">线性代数
        <input type="checkbox" value="3" name="item" onClick="onCheckBox(this)">数据结构与算法
        <input type="checkbox" value="4" name="item" onClick="onCheckBox(this)">大学物理
        <input type="checkbox" value="5" name="item" onClick="onCheckBox(this)">概率论
        <input type="checkbox" value="6" name="item" onClick="onCheckBox(this)">机械制图
        <br><span>生活区</span>
        <input type="checkbox" value="7" name="item" onClick="onCheckBox(this)">寻物启事与失物招领
        <input type="checkbox" value="8" name="item" onClick="onCheckBox(this)">找寻组织与兴趣交流
        <input type="checkbox" value="9" name="item" onClick="onCheckBox(this)">心理咨询
        <input type="checkbox" value="10" name="item" onClick="onCheckBox(this)">跳蚤市场
        <br><button>发布</button>
    </form>
{% endblock %}

{% block head %}
    {{ block.super }}
    <script language="javascript" type="text/javascript">
    var maxChoices = 3;
    var flag = 0;
    function onCheckBox(checkbox) {
        var items = document.getElementsByName("item");
        if(checkbox.checked) {
            flag ++;
        }
        else {
            flag --;
        }
        if(flag < maxChoices) {
            for(var i=0; i<items.length; i++) {
                if(!items[i].checked) {
                    items[i].disabled = false;
                }
            }
        }
        else {
            for(var i=0; i<items.length; i++) {
                if(!items[i].checked) {
                    items[i].disabled = true;
                }
            }
        }
    }
</script>
{% endblock %}

{% block css_code %}
    <style type="text/css">
        .toolbar {
            border: 1px solid #ccc;
        }
        .text {
            border: 1px solid #ccc;
            height: 400px;
        }
        .userlabels {
            width: 60px ;
        }
    </style>
{% endblock %}

{% block js_code %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    {#    以下为富文本相关   #}
    <script type="text/javascript" src="/static/js/wangEditor/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor1 = new E('#div2')  // 两个参数也可以传入 elem 对象，class 选择器
        editor1.customConfig.uploadImgShowBase64 = true //upload pictures
        editor1.customConfig.colors = [
            '#000000',
            '#eeece0',
            '#1c487f',
            '#4d80bf',
            '#c24f4a',
            '#6b8e23',
            '#7b5ba1',
            '#46acc8',
            '#f9963b',
            '#ffffff',
            '#ffff00',
            '#ffc0cb',
        ]
        {#editor1.create()#}
        var $text1 = $('#text1')
        editor1.customConfig.onchange = function (html) {
            // 监控变化，同步更新到 textarea
            $text1.val(html)
        }
        editor1.create()
        // 初始化 textarea 的值
        $text1.val(editor1.txt.html())
    </script>
{% endblock %}

web/templates/Discussion/base_discussion.html
{% extends 'base.html' %}

web/templates/Discussion/discussions.html
{% extends 'base.html' %}

{% block head %}
    <div>
        <a href="{% url 'app1:add_discussion' %}">提问</a> &nbsp;
    </div>
    <form action="{% url 'app1:search_discussion' %}" method="post">
        {% csrf_token %}
        <div class="searcher">
        <input type="text" name="search_ob" placeholder="请输入您想要搜索的问题...">
        <button>Search</button>
        </div>
    </form>
    <hr>
    <span>学习区</span><br>
    <a href="{% url 'app1:get_d_label' 1 %}">高等数学</a>&nbsp;
    <a href="{% url 'app1:get_d_label' 2 %}">线性代数</a>&nbsp;
    <a href="{% url 'app1:get_d_label' 3 %}">数据结构与算法</a>&nbsp;
    <a href="{% url 'app1:get_d_label' 4 %}">大学物理</a>&nbsp;
    <a href="{% url 'app1:get_d_label' 5 %}">概率论</a>
    <a href="{% url 'app1:get_d_label' 6 %}">机械制图</a><br>
    <span>生活区</span><br>
    <a href="{% url 'app1:get_d_label' 7 %}">寻物启事与失物招领</a>
    <a href="{% url 'app1:get_d_label' 8 %}">找寻组织与兴趣交流</a>
    <a href="{% url 'app1:get_d_label' 9 %}">心理咨询</a>
    <a href="{% url 'app1:get_d_label' 10 %}">跳蚤市场</a>
    <hr>
{% endblock %}

{% block content %}

    <ul>
        {% for discussion in discussions %}
            <li><a href="{% url 'app1:show_discussion' discussion.id 0 %}">{{ discussion.title }}</a></li>
        {% empty %}
            <li>No Discussion ! </li>
        {% endfor %}
    </ul>
    {#    nav里为分页器 #}
    <nav aria-label="Page navigation">
        <ul class="pagination">

            {% if page_now == 1 %}
                <li class="disabled">
                    <span>
                        <span aria-hidden="true">&laquo;</span>
                    </span>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'app1:discussions' %}?page={{ page_objects.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for page in page_range %}
                <li>
                    <a href="{% url 'app1:discussions' %}?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}

            {% if page_objects.has_next %}
                <li>
                    <a href="{% url 'app1:discussions' %}?page={{ page_objects.next_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span>
                        <span aria-hidden="true">&raquo;</span>
                    </span>
                </li>
            {% endif %}
        </ul>
    </nav>

{% endblock %}

web/templates/Discussion/discussions_with_label.html
{% extends 'base.html' %}

{% block content %}
    {% if label_type == '1' %}
        <h3>高等数学</h3>
    {% elif label_type == '2' %}
        <h3>线性代数</h3>
    {% elif label_type == '3' %}
        <h3>数据结构与算法</h3>
    {% elif label_type == '4' %}
        <h3>大学物理</h3>
    {% elif label_type == '5' %}
        <h3>概率论</h3>
    {% elif label_type == '6' %}
        <h3>机械制图</h3>
    {% elif label_type == '7' %}
        <h3>寻物启事与失物招领</h3>
    {% elif label_type == '8' %}
        <h3>找寻组织与兴趣交流</h3>
    {% elif label_type == '9' %}
        <h3>心理咨询</h3>
    {% elif label_type == '10' %}
        <h3>跳蚤市场</h3>
    {% endif %}
    <p>最新</p>
    <ul>
        {% for discussion in discussions %}
            <li><a href="{% url 'app1:show_discussion' discussion.id 0 %}">{{ discussion.title }}</a></li>
        {% empty %}
            <li>No Discussion ! </li>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/Discussion/my_collected_discussions.html
{% extends 'base.html' %}

{% block content %}
    <h3>我收藏的讨论</h3><br>
    <ul>
        {% for discussion in discussions %}
            <li>
                <div><a href="{% url 'app1:show_discussion' discussion.id 0 %}">{{ discussion.title }}</a></div>
                <a href="{% url 'app1:uncollect_discussion' discussion.id %}" style="float: right">取消收藏</a>
                <hr>
            </li>
            {% empty %}
            <li>您还没有收藏任何问题哦~</li>
        {% endfor %}
    </ul>

{% endblock %}

web/templates/Discussion/my_discussion.html
{% extends 'base.html' %}

{% block content %}
    <ul>
        {% for discussion in discussions %}
            <li><a href="{% url 'app1:show_discussion' discussion.id 0 %}">{{ discussion.title }}</a></li>
        {% empty %}
            <li>No discussion!</li>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/Discussion/search_consequence.html
{% extends 'base.html' %}

{% block head %}
    <form action="{% url 'app1:search_discussion' %}" method="post">
        {% csrf_token %}
        <div class="searcher">
        <input type="text" name="search_ob" placeholder="请输入您想要搜索的问题...">
        <button>Search</button>
        </div>
    </form>
{% endblock %}

{% block content %}
    <h4>搜索结果</h4>
    <p>最多回复</p>
    <ul>
        {% for aim_discussion in aim_discussions %}
            <li><a href="{% url 'app1:show_discussion' aim_discussion.id 0 %}">
                {{ aim_discussion.title }}
            </a></li>
        {% empty %}
            <span>没有找到这个问题哦..</span>
            <a href="{% url 'app1:add_discussion' %}">我要提问?</a>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/Discussion/show_discussion.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <h2>{{ discussion.title }}</h2>
    <div>提问者：<a href="{% url 'app1:his_home' discussion.owner.id %}">{{ discussion.owner.name }}</a></div>
    {% if is_author %}
        <a href="{% url 'app1:delete_discussion' discussion_id=discussion.id %}">删除</a>
    {% endif %}
    <hr>
    <p>{{ discussion.content | safe }}</p>  {# 为解决html内容无法显示的问题，添加“safe”，但也使网站易被攻击 #}
    <hr>


    {% if is_login %}
        <span id="like" star_id="{{ discussion.owner.id }}" fan_id="{{ user.id }}">关注提问者</span> &nbsp;
        <span id="recommend" discussion_id="{{ discussion.id }}" fan_id="{{ user.id }}" >赞</span> &nbsp;
        <span id="mark" discussion_id="{{ discussion.id }}" fan_id="{{ user.id }}" >收藏</span> &nbsp;
        <span>{{ discussion.comments_num }}评论</span>
        <br> <span id="AttentionHint"></span>
    {% endif %}

    <hr>
    {% if is_label %}
        标签:
        {% for label in labels %}
            {{ label }}&nbsp;
        {% endfor %}
    {% endif %}
    <hr>
    <h5><div><a href="{% url 'app1:add_discussion_comment' discussion_id=discussion.id %}">添加评论</a></div></h5>
    <a href="{% url 'app1:show_discussion' discussion.id 0 %}">最热评论</a>&nbsp;
    <a href="{% url 'app1:show_discussion' discussion.id 1 %}">最新评论</a>
    <ul>
        {% for comment in comments %}
            <li>
                <div>
                    <span><a href="{% url 'app1:his_home' comment.owner.id %}">{{ comment.owner.name }}</a></span>
                    <br>
                    <p>{{ comment.content }}</p>

                    {% for comment_response in comment_responses %}
                        {% if comment_response.comment == comment %}
                            {% if comment_response.type == 0 %}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{% url 'app1:his_home' comment_response.owner.id %}" style="display: inline; color: dimgray">
                                    {{ comment_response.owner.name }}
                                </a>
                                <p style="display: inline; color: #999999">:{{ comment_response.content }}</p>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <h6 style="display: inline; color: #999999">{{ comment_response.add_time }}</h6>
                                <a href="{% url 'app1:res_dis_res' comment_response.id 1 discussion.id %}" style="display: inline; color: #999999">回复</a>
                                <br>
                            {% else %}
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{% url 'app1:his_home' comment_response.owner.id %}" style="display: inline; color: dimgray">
                                    {{ comment_response.owner.name }}
                                </a>回复了
                                <a href="{% url 'app1:his_home' comment_response.comment_res.owner.id %}" style="display: inline; color: dimgray">
                                    {{ comment_response.comment_res.owner.name }}
                                </a>
                                <p style="display: inline; color: #999999">:{{ comment_response.content }}</p>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <h6 style="display: inline; color: #999999">{{ comment_response.add_time }}</h6>
                                <a href="{% url 'app1:res_dis_res' comment_response.id 1 discussion.id %}" style="display: inline; color: #999999">回复</a>
                                <br>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {{ comment.likes_num }}
                    <a href="{% url 'app1:recommend_discussion_response' comment.id user.id %}">
                        点赞
                    </a>&nbsp;&nbsp;
                    <a href="{% url 'app1:res_dis_res' comment.id 0 discussion.id %}">回复</a>&nbsp;&nbsp;&nbsp;

                    {% if user.id == comment.owner.id  %}
                        <span><a href="{% url 'app1:delete_comment' comment.id %}">删除评论</a></span>
                    {% endif %}
                    <h6>回答于{{ comment.add_time }}</h6>
                    <span id="AttentionHint2"></span>
                </div><br>
            </li>
        {% empty %}
            <li>该文章目前还没有评论...</li>
        {% endfor %}
    </ul>

{% endblock %}

{% block js_code %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/my_js/discussion/show_discussion.js' %}"></script>
{% endblock %}