web/app1/urls.py
from django.conf.urls import url

from app1 import views

urlpatterns = [
    url(r'^helloworld/', views.helloworld, name='helloworld'),

    #url(r'^addarticle/', views.addarticle, name='addarticle'),

    url(r'^register/', views.register, name = 'register'),

    url(r'^get_verify_code/', views.get_verify_code, name = 'get_verify_code'),

    url(r'^checkusername/', views.check_username, name = 'check_username'),

    url(r'^login/', views.login, name = 'login'),

    url(r'^home/', views.home, name = 'home'),

    url(r'^logout/', views.logout, name = 'logout'),

    url(r'^addarticle/', views.add_article, name = 'add_article'),

    url(r'^article/(?P<article_id>\d+)', views.show_article, name = 'show_article'),

    url(r'^addlikerelationship/', views.add_like_relationship, name='add_like_relationship'),

    url(r'^recommendarticle/', views.recommend_article, name='recommend_article'),

    url(r'^markarticle/', views.mark_article, name='mark_article'),

    url(r'^addicon/', views.add_icon, name = 'add_icon'),

    url(r'^myblog/', views.my_blog, name = 'my_blog'),

    url(r'^changepassword/', views.change_password, name='change_password'),

    url(r'^changepasswordcheck/', views.change_password_check, name='change_password_check'),

    url(r'^deletearticle/(?P<article_id>\d+)/', views.delete_article, name = 'delete_article'),

    url(r'^personalinformation/', views.personal_information, name = 'personal_information'),

    url(r'^blogs/(?P<order_type>\d+)/', views.blogs, name = 'blogs'),

    url(r'^adddiscussion/', views.add_discussion, name = 'add_discussion'),

    url(r'^mydiscussion/', views.my_discussion, name='my_discussion'),

    url(r'^show_discussion/(?P<discussion_id>\d+)/(?P<order_type>\d+)/', views.show_discussion, name='show_discussion'),

    url(r'^discussions/', views.discussions, name = 'discussions'),

    url(r'^addarticlecomment/(?P<article_id>\d+)/', views.add_article_comment, name = 'add_article_comment'),

    url(r'^deletediscussion/(?P<discussion_id>\d+)/', views.delete_discussion, name = 'delete_discussion'),

    url(r'^recommenddiscussion/', views.recommend_discussion, name='recommend_discussion'),

    url(r'^markdiscussion/', views.mark_discussion, name='mark_discussion'),

    url(r'^adddiscussioncomment/(?P<discussion_id>\d+)/', views.add_discussion_comment, name = 'add_discussion_comment'),

    url(r'^recommenddiscussionresponse/(?P<comment_id>\d+)/(?P<fan_id>\d+)/', views.recommend_discussion_response, name = 'recommend_discussion_response'),

    url(r'^explore/', views.explore, name = 'explore'),

    url(r'^mycollectedarticles/', views.my_collected_articles, name = 'my_collected_articles'),

    url(r'^myfans/', views.my_fans, name = 'my_fans'),

    url(r'^myidols/', views.my_idols, name = 'my_idols'),
    #add functions
    url(r'^editblog/(?P<article_id>\d+)/', views.edit_blog, name='edit_blog'),

    url(r'^searchblog/', views.search_blog, name='search_blog'),

    url(r'^searchdiscussion/', views.search_discussion, name='search_discussion'),

    url(r'^searchuser/', views.search_user, name='search_user'),

    url(r'^hishome/(?P<person_id>\d+)/', views.his_home, name='his_home'),

    url(r'^hisblog/(?P<person_id>\d+)/', views.his_blog, name='his_blog'),

    url(r'^hisdiscussion/(?P<person_id>\d+)/', views.his_discussion, name='his_discussion'),

    url(r'^hisidols/(?P<person_id>\d+)/', views.his_idols, name='his_idols'),

    url(r'^hisfans/(?P<person_id>\d+)/', views.his_fans, name='his_fans'),

    url(r'^mycollecteddiscussions/', views.my_collected_discussions, name='my_collected_discussions'),

    url(r'^deletecomment/(?P<comment_id>\d+)/', views.delete_comment, name='delete_comment'),

    url(r'^deleteblogcomment/(?P<comment_id>\d+)/', views.delete_blog_comment, name='delete_blog_comment'),

    url(r'^unlikerelationship/', views.unlike_relationship, name='unlike_relationship'),

    url(r'^messagebox/', views.message_box, name='message_box'),

    url(r'^getlabel/(?P<label_type>\d+)/', views.get_label, name='get_label'),

    url(r'^getdlabel/(?P<label_type>\d+)/', views.get_d_label, name='get_d_label'),

    url(r'^addlabel/', views.add_label, name = 'add_label'),

    url(r'^randomdiscussion/', views.random_discussion, name='random_discussion'),

    url(r'^randomblog/', views.random_blog, name='random_blog'),

    url(r'^calculatehot/', views.calculate_hot, name='calculate_hot'),#刷新博客热度排名

    url(r'^chat/(?P<receiver_id>\d+)/(?P<sender_id>\d+)/', views.chat, name='chat'),

    url(r'^chatrooms/', views.chatrooms, name='chatrooms'),

    url(r'^deletechat/(?P<room_id>\d+)/', views.delete_chat, name='delete_chat'),

    url(r'^uncollectblog/(?P<article_id>\d+)/', views.uncollect_blog, name='uncollect_blog'),

    url(r'^uncollectdiscussion/(?P<discussion_id>\d+)/', views.uncollect_discussion, name='uncollect_discussion'),

    url(r'^resdisres/(?P<comment_id>\d+)/(?P<type>\d+)/(?P<discussion_id>\d+)/', views.res_dis_res, name='res_dis_res'),

    # url(r'^refreshlabel/', views.refresh_label, name = 'refresh_label'),

    url(r'^$', views.index, name='index'),

]

web/web1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('app1.urls', namespace='app1')),
]

web/templates/UserManager/base_user.html
{% extends 'base.html' %}

web/templates/UserManager/change_password.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'app1:change_password'  %}" method="post">
        {% csrf_token %}
        <span>新密码：</span> <input type="password" name="password1" placeholder="请输入您的密码"> <br>
        <span>请确认您的密码：</span> <input type="password" name="password2" placeholder="请再次输入您的密码"> <br>
        <input type="hidden" name="u_token" value={{ u_token }}>
        <button>提交</button>
    </form>
{% endblock %}

web/templates/UserManager/change_password_check.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'app1:change_password_check' %}" method="post">
        {% csrf_token %}
        <span>请输入您的密码：</span> <input type="password" name="password" placeholder="请输入您的密码"> <br>
        <button>提交</button>
    </form>
{% endblock %}

web/templates/UserManager/chat.html
{% extends 'base.html' %}

{% block content %}
    <h4>{{ receiver.name }}</h4>
    <div style="overflow: scroll; width: 1000px; height: 400px;">
        {% if correspond %}
            {% for message in messages %}
                {% if not message.message_type %}
                    <div style="float: left; clear: both">
                        {{ receiver.name }} {{ message.message_time }}<br>
                        {{ message.message }}
                    </div>
                {% else %}
                    <div style="float: right; clear: both">
                        {{ sender.name }} {{ message.message_time }}<br>
                        {{ message.message }}
                    </div>
                {% endif %}
                <br>
            {% endfor %}
        {% else %}
            {% for message in messages %}
                {% if not message.message_type %}
                    <div style="float: right; clear: both">
                        {{ sender.name }} {{ message.message_time }}<br>
                        {{ message.message }}
                    </div>
                {% else %}
                    <div style="float: left; clear: both">
                        {{ receiver.name }} {{ message.message_time }}<br>
                        {{ message.message }}
                    </div>
                {% endif %}
                <br>
            {% endfor %}
        {% endif %}
    </div>
    <div>
        <form action="{% url 'app1:chat' receiver.id sender.id %}" method="post">
            {% csrf_token %}
            <textarea type="text" name="new_message" style="width: 954px; height: 100px;"></textarea>
            <button>发送</button>
        </form>
    </div>
{% endblock %}

web/templates/UserManager/chatrooms.html
{% extends 'base.html' %}

{% block content %}
    {% for receiver in receivers %}
        <div>
            <style>#icon{width:40px; height: 40px; border-radius: 50%}</style>
            <img id="icon" src="/static/uploadfiles/{{ receiver.icon }}" alt="icon">
            <a href="{% url 'app1:chat' receiver.id user.id %}">{{ receiver.name }}</a>
            {% for room in rooms %}
                {% if room.receiver_id == receiver.id %}
                    {{ room.sender_unread_num }}
                    <a href="{% url 'app1:delete_chat' room.id %}" style="float: right;">删除会话</a>
                {% endif %}
                {% if room.sender_id == receiver.id %}
                    {{ room.receiver_unread_num }}
                    <a href="{% url 'app1:delete_chat' room.id %}" style="float: right;">删除会话</a>
                {% endif %}
            {% endfor %}
        </div>
    {% empty %}
        <p>还没有聊天哦~</p>
    {% endfor %}

{% endblock %}

web/templates/UserManager/his_home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <style>#icon{width: 200px; height: 200px; border-radius: 50%}</style>
    <style>#sex{width: 30px; height: 30px; border-radius: 50%; top:360px; left:200px; position: absolute}</style>
    <h1>{{ user.name }}</h1>
    <img id="icon" src="{{ icon_url }}" alt="icon">
    {% if user.sex == 1 %}
        <img id="sex" src="/static/uploadfiles/system/male.png" alt="sex">
    {% elif user.sex == 2 %}
        <img id="sex" src="/static/uploadfiles/system/female.png" alt="sex">
    {% endif %}
    <h4>{{ user.motto }}</h4>

    <span id="like" star_id="{{ user.id }}" fan_id="{{ me.id }}">关注</span>
    <span id="unlike" star_id="{{ user.id }}" fan_id="{{ me.id }}">取消关注</span>

    <span id="AttentionHint"></span>
    <a href="{% url 'app1:chat' user.id me.id %}">私信</a>
    <ul>
        <li><a href="{% url 'app1:his_blog' user.id %}">{{ user.name }}的博客</a></li>
        <li><a href="{% url 'app1:his_discussion' user.id %}">{{ user.name }}的讨论</a></li>
        <li><a href="{% url 'app1:his_fans' user.id %}">{{ user.name }}的粉丝</a></li>
        <li><a href="{% url 'app1:his_idols' user.id %}">{{ user.name }}的关注</a></li>
    </ul>
{% endblock %}

{% block js_code %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/my_js/UserManager/add_user.js' %}"></script>
{% endblock %}

web/templates/UserManager/login.html
{% extends 'base_null.html' %}

{% load static %}

{% block content %}
    <div id='login-box'>
        <h1>Login</h1>
        <form action="{% url 'app1:login' %}" method="post">
            {% csrf_token %}
            <div class="item">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                <input type="text" name="username" placeholder='username'>
            </div>
            <div class="item">
                <i class="fa fa-key" aria-hidden="true"></i>
                <input type="password" name="password" placeholder='password'>  {# type=password可使字符加密显示 #}
            </div>
            <button>Login</button>
{#            <a id="password_change" href="{% url 'app1:forget_password' %}">忘记密码</a>#}
        </form>
    </div>
{% endblock %}

{% block css_code %}
{#    <link rel="stylesheet" href="/static/css/login.css">#}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">   {# 效果和上面被注掉的相同 只不过使用了相对路径 #}
    <link rel="stylesheet" href="/static/css/font-awesome.css">
    <style type="text/css">
        #password_change {
            position: absolute ;
            top: 460px ;
            left: 890px ;
        }
    </style>
{% endblock %}

web/templates/UserManager/message_box.html
{% extends 'UserManager/base_user.html' %}

{% block content %}
    <form action="{% url 'app1:message_box' %}" method="post">
        {% csrf_token %}
        <div>
            <button>已读</button>
        </div>
        <hr>
    </form>
    <div>
        {% for message in messages %}


            {% if message.message_type == 0 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 给你的博客
                <a href="{% url 'app1:show_article' message.article.id %}">{{ message.article.title }}</a> 点赞了!
                <hr>
            {% elif message.message_type == 1 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 在你的博客
                <a href="{% url 'app1:show_article' message.article.id %}">{{ message.article.title }}</a> 下评论了<br>
                "{{ message.article_comment.content }}"
                <hr>
            {% elif message.message_type == 2 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 回答了你的问题
                <a href="{% url 'app1:show_discussion' message.discussion.id 0 %}">{{ message.discussion.title }}</a>
                <br>
                "{{ message.discussion_response.content }}"
                <hr>
            {% elif message.message_type == 3 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 为你在问题
                <a href="{% url 'app1:show_discussion' message.discussion.id 0 %}">{{ message.discussion.title }}</a>
                中的回复
                "{{ message.discussion_response.content }}" 点赞了!
                <hr>
            {% elif message.message_type == 4 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 关注了你!
                <hr>
            {% elif message.message_type == 5 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 回复了你在问题
                <a href="{% url 'app1:show_discussion' message.discussion.id 0 %}">{{ message.discussion.title }}</a>
                中的回复
                "{{ message.discussion_response.content }}"<br>
                "{{ message.discussion_res_res.content }}"
                <hr>
            {% elif message.message_type == 6 %}
                {% if message.have_read == 0 %}NEW!{% endif %}
                <a href="{% url 'app1:his_home' message.sender.id %}">{{ message.sender.name }}</a> 回复了你在问题
                <a href="{% url 'app1:show_discussion' message.discussion.id 0 %}">{{ message.discussion.title }}</a>
                中的回复
                "{{ message.discussion_res_res.content }}"<br>
                "{{ message.discussion_R_R.content }}"
                <hr>


            {% endif %}

        {% empty %}
            <h4>暂时没有消息哦~</h4>
        {% endfor %}
    </div>
{% endblock %}

web/templates/UserManager/my_fans.html
{% extends 'UserManager/base_user.html' %}

{% block content %}
    <h3>我的粉丝</h3><br>
    <ul>
        {% for fan in fans %}
            <li>
{#                <div>粉丝头像</div>#}
                <style>#icon{width:40px; height: 40px; border-radius: 50%}</style>
                <img id="icon" src="/static/uploadfiles/{{ fan.icon }}" alt="icon">
                <a href="{% url 'app1:his_home' fan.id%}">{{ fan.name }}</a>
                {% comment %}<div>{{ fan.name }}</div>{% endcomment %}
                <hr>
            </li>
        {% empty %}
            <li>您目前还没有粉丝哦~</li>
        {% endfor %}
    </ul>

{% endblock %}

web/templates/UserManager/my_idols.html
{% extends 'UserManager/base_user.html' %}

{% load static %}

{% block content %}
    <h3>我的关注</h3><br>
    <ul>
        {% for idol in idols %}
            <li>
{#                <div>头像</div>#}
                <style>#icon{width:40px; height: 40px; border-radius: 50%}</style>
                <img id="icon" src="/static/uploadfiles/{{ idol.icon }}" alt="icon">
                <a href="{% url 'app1:his_home' idol.id%}">{{ idol.name }}</a>
{#                <div>{{ idol.name }}</div>#}
                <hr>
            </li>
        {% empty %}
            <li>您目前还没有关注任何人哦~</li>
        {% endfor %}
    </ul>

{% endblock %}

web/templates/UserManager/personal_information.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'app1:personal_information' %}" method="post">
        {% csrf_token %}
        <div> <span>username: {{ user.name }}</span> </div>
        <div> <span>email: </span> <input name="email" id="email" type="text" value="{{ user.mail }}">  </div>
{#        <div> <span>sex: </span> <input name="sex" id="sex" type="text"> </div>#}
        <div>
            sex:<input type="radio" value="0" name="sex" checked="checked">Unknown
            <input type="radio" value="1" name="sex">Male
            <input type="radio" value="2" name="sex">Female
        </div>
        <div> <span>motto: </span> <input name="motto" id="motto" type="text" value="{{ user.motto }}"></div>
        <button>提交修改</button>
    </form>
{% endblock %}

{% block js_code %}
    <script type="text/javascript">
        var email = document.getElementById("email");
        email.value = "{{ user.mail }}" ;
        var sex = document.getElementById("sex");
        sex.value = "{{ user.sex }}" ;
        var motto = document.getElementById("motto");
        motto.value = "{{ user.motto }}" ;

    </script>
{% endblock %}

web/templates/UserManager/register.html
{% extends 'base_null.html' %}

{% load static %}

{% block content %}
    <div id='login-box'>
        <h1>Register</h1>
        <form action="{% url 'app1:register' %}" method="post" onsubmit="return check()">  <!-- !!! -->
            {% csrf_token %}
            <div class="item">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                <input type="text" id="username" name="username" placeholder='username'>
                <br>
                <span id="username_info"></span>
            </div>
            <div class="item">
                <i class="fa fa-key" aria-hidden="true"></i>
                <input type="password" name="password" placeholder='password'>
            </div>

            <div class="item">
                <i class="fa fa-shield" aria-hidden="true"></i>
                <input type="text" name="verify_code" placeholder="verify_code">
            </div>
            <img id="verify_code" src="{% url 'app1:get_verify_code' %}" alt="verify_code">
            <button>Submit</button>
        </form>

    </div>
{% endblock %}

{% block css_code %}
    <link rel="stylesheet" href="/static/css/register.css">
    <link rel="stylesheet" href="/static/css/font-awesome.css">
    <style type="text/css">
        #verify_code {
            top: 500px ;
            left: 1000px ;
            position: absolute ;
        }
    </style>
{% endblock %}

{% block js_code %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/my_js/UserManager/register.js' %}"></script>
    <script type="text/javascript">
        // 验证码
        var img = document.getElementById("verify_code");
        img.onclick = function () {
            this.src = "{% url 'app1:get_verify_code' %}?t=" + Math.random();
        };
    </script>
{% endblock %}

web/templates/UserManager/search_user.html
{% extends 'base.html' %}

{% block content %}
    <h3>搜索您想要关注的用户..</h3><br>
    <form action="{% url 'app1:search_user' %}" method="post">
        {% csrf_token %}
        <div class="searcher">
            <input type="text" name="search_ob" placeholder="请输入用户名或邮箱...">
            <button>Search</button>
        </div>
    </form>
{% endblock %}

web/templates/UserManager/search_user_consequence.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h3>搜索您想要关注的用户..</h3><br>
    <form action="{% url 'app1:search_user' %}" method="post">
        {% csrf_token %}
        <div class="searcher">
            <input type="text" name="search_ob" placeholder="请输入用户名或邮箱...">
            <button>Search</button>
        </div>
    </form>

    <h4>搜索结果</h4>
    <ul>
        {% for aim_user in aim_users %}
            <li><style>#icon{width:40px; height: 40px; border-radius: 50%}</style>
            <img id="icon" src="/static/uploadfiles/{{ aim_user.icon }}" alt="icon">
                <a href="{% url 'app1:his_home' person_id=aim_user.id %}">{{ aim_user.name }}</a></li>
        {% empty %}
            <span>没有找到此用户..</span>
        {% endfor %}
    </ul>
{% endblock %}