web/app1/urls.py
from django.conf.urls import url

from app1 import views

urlpatterns = [
    url(r'^helloworld/', views.helloworld, name='helloworld'),

    #url(r'^addarticle/', views.addarticle, name='addarticle'),

    url(r'^register/', views.register, name = 'register'),

    url(r'^get_verify_code/', views.get_verify_code, name = 'get_verify_code'),

    url(r'^checkusername/', views.check_username, name = 'check_username'),

    url(r'^login/', views.login, name = 'login'),

    url(r'^home/', views.home, name = 'home'),

    url(r'^logout/', views.logout, name = 'logout'),

    url(r'^addarticle/', views.add_article, name = 'add_article'),

    url(r'^article/(?P<article_id>\d+)', views.show_article, name = 'show_article'),

    url(r'^addlikerelationship/', views.add_like_relationship, name='add_like_relationship'),

    url(r'^recommendarticle/', views.recommend_article, name='recommend_article'),

    url(r'^markarticle/', views.mark_article, name='mark_article'),

    url(r'^addicon/', views.add_icon, name = 'add_icon'),

    url(r'^myblog/', views.my_blog, name = 'my_blog'),

    url(r'^changepassword/', views.change_password, name='change_password'),

    url(r'^changepasswordcheck/', views.change_password_check, name='change_password_check'),

    url(r'^deletearticle/(?P<article_id>\d+)/', views.delete_article, name = 'delete_article'),

    url(r'^personalinformation/', views.personal_information, name = 'personal_information'),

    url(r'^blogs/(?P<order_type>\d+)/', views.blogs, name = 'blogs'),

    url(r'^adddiscussion/', views.add_discussion, name = 'add_discussion'),

    url(r'^mydiscussion/', views.my_discussion, name='my_discussion'),

    url(r'^show_discussion/(?P<discussion_id>\d+)/(?P<order_type>\d+)/', views.show_discussion, name='show_discussion'),

    url(r'^discussions/', views.discussions, name = 'discussions'),

    url(r'^addarticlecomment/(?P<article_id>\d+)/', views.add_article_comment, name = 'add_article_comment'),

    url(r'^deletediscussion/(?P<discussion_id>\d+)/', views.delete_discussion, name = 'delete_discussion'),

    url(r'^recommenddiscussion/', views.recommend_discussion, name='recommend_discussion'),

    url(r'^markdiscussion/', views.mark_discussion, name='mark_discussion'),

    url(r'^adddiscussioncomment/(?P<discussion_id>\d+)/', views.add_discussion_comment, name = 'add_discussion_comment'),

    url(r'^recommenddiscussionresponse/(?P<comment_id>\d+)/(?P<fan_id>\d+)/', views.recommend_discussion_response, name = 'recommend_discussion_response'),

    url(r'^explore/', views.explore, name = 'explore'),

    url(r'^mycollectedarticles/', views.my_collected_articles, name = 'my_collected_articles'),

    url(r'^myfans/', views.my_fans, name = 'my_fans'),

    url(r'^myidols/', views.my_idols, name = 'my_idols'),
    #add functions
    url(r'^editblog/(?P<article_id>\d+)/', views.edit_blog, name='edit_blog'),

    url(r'^searchblog/', views.search_blog, name='search_blog'),

    url(r'^searchdiscussion/', views.search_discussion, name='search_discussion'),

    url(r'^searchuser/', views.search_user, name='search_user'),

    url(r'^hishome/(?P<person_id>\d+)/', views.his_home, name='his_home'),

    url(r'^hisblog/(?P<person_id>\d+)/', views.his_blog, name='his_blog'),

    url(r'^hisdiscussion/(?P<person_id>\d+)/', views.his_discussion, name='his_discussion'),

    url(r'^hisidols/(?P<person_id>\d+)/', views.his_idols, name='his_idols'),

    url(r'^hisfans/(?P<person_id>\d+)/', views.his_fans, name='his_fans'),

    url(r'^mycollecteddiscussions/', views.my_collected_discussions, name='my_collected_discussions'),

    url(r'^deletecomment/(?P<comment_id>\d+)/', views.delete_comment, name='delete_comment'),

    url(r'^deleteblogcomment/(?P<comment_id>\d+)/', views.delete_blog_comment, name='delete_blog_comment'),

    url(r'^unlikerelationship/', views.unlike_relationship, name='unlike_relationship'),

    url(r'^messagebox/', views.message_box, name='message_box'),

    url(r'^getlabel/(?P<label_type>\d+)/', views.get_label, name='get_label'),

    url(r'^getdlabel/(?P<label_type>\d+)/', views.get_d_label, name='get_d_label'),

    url(r'^addlabel/', views.add_label, name = 'add_label'),

    url(r'^randomdiscussion/', views.random_discussion, name='random_discussion'),

    url(r'^randomblog/', views.random_blog, name='random_blog'),

    url(r'^calculatehot/', views.calculate_hot, name='calculate_hot'),#刷新博客热度排名

    url(r'^chat/(?P<receiver_id>\d+)/(?P<sender_id>\d+)/', views.chat, name='chat'),

    url(r'^chatrooms/', views.chatrooms, name='chatrooms'),

    url(r'^deletechat/(?P<room_id>\d+)/', views.delete_chat, name='delete_chat'),

    url(r'^uncollectblog/(?P<article_id>\d+)/', views.uncollect_blog, name='uncollect_blog'),

    url(r'^uncollectdiscussion/(?P<discussion_id>\d+)/', views.uncollect_discussion, name='uncollect_discussion'),

    url(r'^resdisres/(?P<comment_id>\d+)/(?P<type>\d+)/(?P<discussion_id>\d+)/', views.res_dis_res, name='res_dis_res'),

    # url(r'^refreshlabel/', views.refresh_label, name = 'refresh_label'),

    url(r'^$', views.index, name='index'),

]

web/web1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('app1.urls', namespace='app1')),
]

web/templates/Blog/add_article.html
{% extends 'Blog/base_blog.html' %}

{% load static %}

{% block head %}
    <script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript">
        tinyMCE.init({
            "mode": "textareas",
            "theme": "advanced",
            "width": 800,
            "height": 600,
        })
    </script>
    <script language="javascript" type="text/javascript">

        var maxChoices = 3;
        var flag = 0;

        function onCheckBox(checkbox) {
            var items = document.getElementsByName("item");
            if (checkbox.checked) {
                flag++;
            } else {
                flag--;
            }
            if (flag < maxChoices) {
                for (var i = 0; i < items.length; i++) {
                    if (!items[i].checked) {
                        items[i].disabled = false;
                    }
                }
            } else {
                for (var i = 0; i < items.length; i++) {
                    if (!items[i].checked) {
                        items[i].disabled = true;
                    }
                }
            }
        }

    </script>

{% endblock %}

{% block content %}
    <form action="{% url 'app1:add_article' %}" id="formlist" method="post" onsubmit="return check()">
        {% csrf_token %}
        <span>标题：</span> <input type="text" name="title" value="标题.."> <br>
        {#        <span>内容：</span> <textarea name="content"></textarea><hr>#}
        <div id="div1" class="toolbar">
        </div>
        <div style="padding: 5px 0; color: #ccc"></div>
        <div id="div2" class="text"> <!--可使用 min-height 实现编辑区域自动增加高度-->
            <p>请输入内容..</p>
        </div>
        <textarea name="content" id="text1" style="display:none"></textarea>
        <span>添加到分区,让你的文章被更多人看到!</span> <br>
        <span>学科区</span><br>
        <input type="checkbox" value="1" name="item" onClick="onCheckBox(this)">高等数学
        <input type="checkbox" value="2" name="item" onClick="onCheckBox(this)">线性代数
        <input type="checkbox" value="3" name="item" onClick="onCheckBox(this)">数据结构与算法
        <input type="checkbox" value="4" name="item" onClick="onCheckBox(this)">大学物理
        <input type="checkbox" value="5" name="item" onClick="onCheckBox(this)">概率论
        <br>
        <span>专业区</span><br>
        <input type="checkbox" value="6" name="item" onClick="onCheckBox(this)">计算机科学与技术
        <input type="checkbox" value="7" name="item" onClick="onCheckBox(this)">机电工程与自动化
        <input type="checkbox" value="8" name="item" onClick="onCheckBox(this)">电子与信息工程
        <input type="checkbox" value="9" name="item" onClick="onCheckBox(this)">经济管理
        <input type="checkbox" value="10" name="item" onClick="onCheckBox(this)">材料与环境
        <br>
        <hr>
        为文章添加专属标签,可使文章更容易被搜索到哦~ :
        <input type="text" name="tag2"> <br>
        <button>发布</button>
        {#        <input type="button" id="submit_button" value="提交">#}
    </form>

    {# 个人标签相关 #}
    {#    <hr>#}
    {#    <span>已添加标签:</span>#}
    {#    <ul id="selectedlabels">#}
    {##}
    {#    </ul>#}
    {#    <span id="backout">撤销</span> <br>#}
    <span>我的分区:</span>
    <ul id="ulabels">
        {% for label in userlabels %}
            <li class="userlabels not_selected">
                {{ label.name }}
            </li>
        {% endfor %}
    </ul>

    {# 添加新的个人标签 #}
    <input type="text" id="label_name" name="label_name"> <br>
    <button id="add_label_button" name="add_label_button">添加分区</button>
    <div id="add_label_info"></div>

{% endblock %}

{% block css_code %}
    <style type="text/css">
        .toolbar {
            border: 1px solid #ccc;
        }

        .text {
            border: 1px solid #ccc;
            height: 400px;
        }

        .userlabels {
            width: 60px;
        }
    </style>
{% endblock %}

{% block js_code %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/my_js/label/add_label.js"></script>
    {#    以下为富文本相关   #}
    <script type="text/javascript" src="/static/js/wangEditor/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor1 = new E('#div2')  // 两个参数也可以传入 elem 对象，class 选择器
        editor1.customConfig.uploadImgShowBase64 = true //upload pics
        editor1.customConfig.colors = [
            '#000000',
            '#eeece0',
            '#1c487f',
            '#4d80bf',
            '#c24f4a',
            '#6b8e23',
            '#7b5ba1',
            '#46acc8',
            '#f9963b',
            '#ffffff',
            '#ffff00',
            '#ffc0cb',
        ]
        {#editor1.create()#}
        var $text1 = $('#text1')
        editor1.customConfig.onchange = function (html) {
            // 监控变化，同步更新到 textarea
            $text1.val(html)
        }
        editor1.create()
        // 初始化 textarea 的值
        $text1.val(editor1.txt.html())
    </script>
{% endblock %}

web/templates/Blog/add_comment.html
{% extends 'Blog/base_blog.html' %}

{% load static %}

{% block head %}
<script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        "mode": "textareas",
        "theme": "advanced",
        "width": 800,
        "height": 600,
    })
</script>
{% endblock %}

{% block content %}
    <form action="{% url 'app1:add_article_comment' article_id=article_id %}" method="post">
        {% csrf_token %}
        <span>内容：</span> <textarea name="content"></textarea>
        <button>保存</button>
    </form>
{% endblock %}

web/templates/Blog/addarticle.html
{#{% extends 'base.html' %}#}
{##}
{#{% load static %}#}
{#{% block head %}#}
{#<script type="text/javascript" src="/static/tinymce/tinymce.min.js"></script>#}
{#<script type="text/javascript">#}
{#    tinyMCE.init({#}
{#        "mode": "textareas",#}
{#        "theme": "advanced",#}
{#        "width": 800,#}
{#        "height": 600,#}
{#    })#}
{#</script>#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#    <form action="{% url 'app1:addarticle' %}" method="post">#}
{#        {% csrf_token %}#}
{#        <span>标题：</span> <input type="text" name="title"> <br>#}
{#        <span>内容：</span> <textarea name="content"></textarea>#}
{#        <button>保存</button>#}
{#    </form>#}
{#{% endblock %}#}

web/templates/Blog/base_blog.html
{% extends 'base.html' %}

web/templates/Blog/blogs.html
{% extends 'Blog/base_blog.html' %}

{% block head %}
    <div>
        <a href="{% url 'app1:add_article' %}">写博客</a> &nbsp;
{#        <span>...搜索...</span>#}
    </div>
    <form action="{% url 'app1:search_blog' %}" method="post">
        {% csrf_token %}
        <div class="searcher">
        <input type="text" name="search_ob" placeholder="请输入您想要搜索的博客...">
        <button>Search</button>
        </div>
    </form>
    <hr>
    <span>学科</span><br>
    <a href="{% url 'app1:get_label' 1 %}">高等数学</a>&nbsp;
    <a href="{% url 'app1:get_label' 2 %}">线性代数</a>&nbsp;
    <a href="{% url 'app1:get_label' 3 %}">数据结构与算法</a>&nbsp;
    <a href="{% url 'app1:get_label' 4 %}">大学物理</a>&nbsp;
    <a href="{% url 'app1:get_label' 5 %}">概率论</a>
    <br><span>专业</span><br>
    <a href="{% url 'app1:get_label' 6 %}">计算机科学与技术</a>&nbsp;
    <a href="{% url 'app1:get_label' 7 %}">机电工程与自动化</a>&nbsp;
    <a href="{% url 'app1:get_label' 8 %}">电子与信息工程</a>
    <a href="{% url 'app1:get_label' 9 %}">经济管理</a>
    <a href="{% url 'app1:get_label' 10 %}">材料与环境</a>
    <hr>
    <div>
        <a href="{% url 'app1:blogs' 0 %}">最热文章</a> &nbsp;
        <a href="{% url 'app1:blogs' 1 %}">最新文章</a>
    </div>
{% endblock %}

{% block content %}

    <ul>
        {% for article in page_objects %}
            <li>
                <a href="{% url 'app1:show_article' article_id=article.id %}">{{ article.title }}</a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span>{{ article.tag2 }}</span>
                <br>
                <span>{{ article.content }}</span>
            </li>
        {% empty %}
            <li>No Article ! </li>
        {% endfor %}
    </ul>
    {#    nav里为分页器 #}
    <nav aria-label="Page navigation">
        <ul class="pagination">

            {% if page_now == 1 %}
                <li class="disabled">
                    <span>
                        <span aria-hidden="true">&laquo;</span>
                    </span>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'app1:blogs' 0 %}?page={{ page_objects.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for page in page_range %}
                <li>
                    <a href="{% url 'app1:blogs' 0 %}?page={{ page }}">{{ page }}</a>
                </li>
            {% endfor %}

            {% if page_objects.has_next %}
                <li>
                    <a href="{% url 'app1:blogs' 0 %}?page={{ page_objects.next_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span>
                        <span aria-hidden="true">&raquo;</span>
                    </span>
                </li>
            {% endif %}
        </ul>
    </nav>

{#    {% for blog in blogs %}#}
{#        <div blog_id="{{ blog.id }}" class="blog">#}
{#            <div>{{ blog.title }} &nbsp&nbsp&nbsp&nbsp&nbsp {{ blog.author.name }}</div>#}
{#            <br>#}
{#            <p>{{ blog.content }}</p>#}
{#        </div>#}
{#        <hr>#}
{#    {% endfor %}#}
{% endblock %}

{% load static %}
{% block js_code %}
    <script type="text/javascript" src="{% static 'js/my_js/blog/blogs.js' %}"></script>
{% endblock %}

web/templates/Blog/blogs_with_label.html
{% extends 'Blog/base_blog.html' %}

{% block content %}
    {% if label_type == '1' %}
        <h3>高等数学</h3>
    {% elif label_type == '2' %}
        <h3>线性代数</h3>
    {% elif label_type == '3' %}
        <h3>数据结构与算法</h3>
    {% elif label_type == '4' %}
        <h3>大学物理</h3>
    {% elif label_type == '5' %}
        <h3>概率论</h3>
    {% elif label_type == '6' %}
        <h3>计算机科学与技术</h3>
    {% elif label_type == '7' %}
        <h3>机电工程与自动化</h3>
    {% elif label_type == '8' %}
        <h3>电子与信息工程</h3>
    {% elif label_type == '9' %}
        <h3>经济管理</h3>
    {% elif label_type == '10' %}
        <h3>材料与环境</h3>
    {% endif %}
    <p>最新</p>
    <ul>
        {% for article in articles %}
            <li><a href="{% url 'app1:show_article' article.id %}">{{ article.title }}</a></li>
        {% empty %}
            <li>No Article ! </li>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/Blog/blogs_with_labels.html
{% extends 'Blog/base_blog.html' %}

{% block content %}
    <span>学科区</span><br>
        <input type="checkbox" class="blabel" id="blabel0">高等数学
        <input type="checkbox" class="blabel" id="blabel1">线性代数
        <input type="checkbox" class="blabel" id="blabel2">数据结构与算法
        <input type="checkbox" class="blabel" id="blabel3">大学物理
        <input type="checkbox" class="blabel" id="blabel4">概率论
        <br>
        <span>专业区</span><br>
        <input type="checkbox" class="blabel" id="blabel5">计算机科学与技术
        <input type="checkbox" class="blabel" id="blabel6">机电工程与自动化
        <input type="checkbox" class="blabel" id="blabel7">电子与信息工程
        <input type="checkbox" class="blabel" id="blabel8">经济管理
        <input type="checkbox" class="blabel" id="blabel9">材料与环境
        <br>
    <p>最新</p>
    <ul>
        {% for article in articles %}
            <li><a href="{% url 'app1:show_article' article.id %}">{{ article.title }}</a></li>
        {% empty %}
            <li>No Article ! </li>
        {% endfor %}
    </ul>
{% endblock %}

{% block js_code %}
    <script type="text/javascript" src="/static/js/my_js/label/choose_blabel.js"></script>
    <script type="text/javascript">
        var str = "#blabel" ;
        for(var i=0;i<=9;i++){
            var str_now = str + i ;
            if((1<<i)&({{ label_type_backup }})){
                $(str_now).prop('checked',true) ;
            } else $(str_now).prop('checked',false) ;
            $(str_now).click(i, function (event) {
                var targ = (1<<event.data)^{{ label_type_backup }} ;
                {#alert(targ) ;#}
                {#window.location.href = "{% url 'app1:get_label' 1 %}" ;#}
                window.location.href = "/getlabel/"+targ+"/" ;
            })
        }
    </script>
{% endblock %}

web/templates/Blog/edit_blog.html
{% extends 'Blog/base_blog.html' %}

{% load static %}

{% block head %}

{% endblock %}

{% block content %}
    <form action="{% url 'app1:edit_blog' article.id %}" method="post">
        {% csrf_token %}
{#        <span>标题：</span> <input type="text" name="title" value="{{ article.title }}"> <br>#}
{#        <span>内容：</span> <textarea name="content">{{ article.content }}</textarea>#}
        <span>标题：</span> <input type="text" name="title" value={{ article.title }}> <br>
        <div id="div1" class="toolbar">
        </div>
        <div style="padding: 5px 0; color: #ccc"> </div>
        <div id="div2" class="text">
            {% autoescape off %}
            <p>{{ article.content }}</p>
            {% endautoescape %}
        </div>
        <textarea id="text1" name="content" style="display: none"></textarea>
        <button>发布</button>
    </form>
{% endblock %}

{% block css_code %}
    <style type="text/css">
        .toolbar {
            border: 1px solid #ccc;
        }
        .text {
            border: 1px solid #ccc;
            height: 400px;
        }
        .userlabels {
            width: 60px ;
        }
    </style>
{% endblock %}

{% block js_code %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    {#    以下为富文本相关   #}
    <script type="text/javascript" src="/static/js/wangEditor/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor1 = new E('#div2')  // 两个参数也可以传入 elem 对象，class 选择器
        {#editor1.create()#}
        var $text1 = $('#text1')
        editor1.customConfig.onchange = function (html) {
            // 监控变化，同步更新到 textarea
            $text1.val(html)
        }
        editor1.create()
        // 初始化 textarea 的值
        $text1.val(editor1.txt.html())
    </script>
{% endblock %}

web/templates/Blog/my_blog.html
{% extends 'Blog/base_blog.html' %}

{% block content %}

    <span>分类:</span>
    <ul>
        {% for ulabel in ulabels %}
            <li>
                <a href="{% url 'app1:my_blog' %}?ulabel_now={{ ulabel.id }}">{{ ulabel.name }}</a>
            </li>
        {% endfor %}
        <li>
            <a href="{% url 'app1:my_blog' %}?ulabel_now=0">全部分类</a>
        </li>
    </ul>

    <hr>

    <ul>
        {% for article in articles %}
            <li>
                <a href="{% url 'app1:show_article' article_id=article.id %}">
                    <h4>{{ article.title }}</h4>
                    {% autoescape off %}
                    <div>{{ article.content }}</div>
                    {% endautoescape %}
                </a>
            </li>
        {% empty %}
            <li>No blogs!</li>
        {% endfor %}
    </ul>

{% endblock %}

web/templates/Blog/my_collected_blogs.html
{% extends 'Blog/base_blog.html' %}

{% block content %}
    <h3>我收藏的博客</h3><br>
    <ul>
        {% for article in articles %}
            <li>
                <div><a href="{% url 'app1:show_article' article_id=article.id %}">{{ article.title }}</a></div>
                <a href="{% url 'app1:uncollect_blog' article.id %}" style="float: right">取消收藏</a>
                <hr>
            </li>
            {% empty %}
            <li>您还没有收藏任何博客哦~</li>
        {% endfor %}
    </ul>

{% endblock %}

web/templates/Blog/search_consequences.html
{% extends 'Blog/base_blog.html' %}

{% block head %}
    <div>
        <a href="{% url 'app1:add_article' %}">写博客</a> &nbsp&nbsp&nbsp&nbsp
    </div>
    <form action="{% url 'app1:search_blog' %}" method="post">
        {% csrf_token %}
        <div class="searcher">
            <input type="text" name="search_ob" placeholder="请输入您想要搜索的博客...">
            <button>Search</button>
        </div>
    </form>
    <hr>
{% endblock %}

{% block content %}
    <h4>搜索结果</h4>
    <p>最热文章</p>
    <ul>
        {% for aim_blog in aim_blogs %}
            <li>
                <hr>
                <a href="{% url 'app1:show_article' article_id=aim_blog.id %}">{{ aim_blog.title }}</a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span>{{ aim_blog.tag2 }}</span>
                <br>
                <span>{{ aim_blog.content }}</span>
            </li>
        {% empty %}
            <span>没有找到这样的博客哦..</span>
            <a href="{% url 'app1:add_article' %}">我要创作?</a>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/Blog/show_article.html
{% extends 'Blog/base_blog.html' %}

{% load static %}

{% block head %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <h2>Title:{{ article.title }}</h2>
    <hr>
    <div>author：<a href="{% url 'app1:his_home' article.author.id %}">{{ article.author.name }}</a></div>
    <hr>
    <p>{{ article.content | safe }}</p>  {# 为解决html内容无法显示的问题，添加“safe”，但也使网站易被攻击 #}
    <h6>发布于{{ article.add_time }}</h6>
    <hr>

{#    <input type="button" value="Delete" formtarget="_blank">#}
{#    <button formtarget="_parent">删除</button>#}          {# 不知道有没有更好的写法，这样写好丑。。。 #}
{#    <a href="{% url 'app:delete_article' article_id=article.id %}">删除</a>    {# kkk，早怎么没想到，一个a标签不就解决了嘛 #}
    {% if is_author %}
{#        <a href="{% url 'app1:delete_article' article_id=article.id %}">删除</a>#}
        <a href="{% url 'app1:delete_article' article_id=article.id %}">删除</a>&nbsp;
        <a href="{% url 'app1:edit_blog' article.id %}">编辑</a>
        <br>
    {% endif %}

    {% if is_login %}
{#        <span id="like" star_id="{{ article.owner.id }}" fan_id="{{ user.id }}">关注</span> &nbsp;&nbsp;&nbsp; <span>推荐</span>#}
        <span id="like" star_id="{{ article.author.id }}" fan_id="{{ user.id }}">关注博主</span> &nbsp;
        <span id="recommend" article_id="{{ article.id }}" fan_id="{{ user.id }}" >{{ article.likes_num }}赞</span> &nbsp;
        <span id="mark" article_id="{{ article.id }}" fan_id="{{ user.id }}" >{{ article.collects_num }}收藏</span> &nbsp;
        <span>{{ article.comments_num }}评论</span> &nbsp;
        <span>{{ article.read_num }}浏览</span> &nbsp;
        <br> <span id="AttentionHint"></span>
    {% endif %}

    <hr>
    {% if is_label %}
        系统标签:
        {% for label in labels %}
            {{ label }}&nbsp;
        {% endfor %}
    {% endif %}

    <hr>
    <div>个人标签:</div>
    <ul>
        {% for ulabel in ulabels %}
            <li>
                {{ ulabel.name }}
            </li>
        {% endfor %}

    </ul>

    <hr>
    <h5><div><a href="{% url 'app1:add_article_comment' article_id=article.id %}">添加评论</a></div></h5>
    <ul>
        {% for comment in comments %}
            <li>
                <div>
                    <a href="{% url 'app1:his_home' comment.owner.id %}">{{ comment.owner.name }}</a> <br>
                    <p>{{ comment.content }}</p>
                    <h6>
                        评论于{{ comment.add_time }}
                        {% if user.id == comment.owner.id  %}
                            <span><a href="{% url 'app1:delete_blog_comment' comment.id %}">删除评论</a></span>
                        {% endif %}
                    </h6>
                </div><br>
            </li>
        {% empty %}
            <li>该文章目前还没有评论...</li>
        {% endfor %}
    </ul>



{% endblock %}

{% block js_code %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/my_js/blog/show_article.js' %}"></script>
{% endblock %}